### ISSUE TITLE
Can't Modify Just Network Description

### ISSUE THREAD

**Issue by hojohn2561** [chariot-dev/chariot#49]
When changing a network's configuration, currently have to change network name. Can't change just its description.

**Comment by Juan-Garcia96** [comment]
[apiFramework 4ee39b8] bugFix: 49 - allow for modification of description without having to alter a network name via PUT request

**Comment by jh3377** [comment]
Not working

**Comment by Juan-Garcia96** [comment]
This works while I test on Yarc.

**Comment by jh3377** [comment]
Getting "Network1 is not a unique networkName in this collection."

**Comment by Juan-Garcia96** [comment]
I just tried it again and it works, can you be more specific in what you are testing? That error seems more like there is already a network named Network1 so you can't change it to that name... Note that modification is a PUT request

**Comment by jh3377** [comment]
What branch are you on?

**Comment by jh3377** [comment]
I'm not changing the name field, just the description.

**Comment by Juan-Garcia96** [comment]
databaseManager (which was merged into master). I know, changing the description and not name is possible. That is what I am testing. Via the PUT request and this payload:
{
"networkName":"testThree",
"description":"change"
}
so the network testThree would just have the description updated

**Comment by jh3377** [comment]
Ok. So it seems like I have to exclude the newNetworkName field. Interesting because I didn't change the payload after pulling from master. It seems like it's currently not reflected in master.

**Comment by jh3377** [comment]
Msater also has the keys in capital (e.g., "NetworkName", "NewName", and "Description", so maybe it's out of date?

**Comment by jh3377** [comment]
Fixed https://github.com/chariot-dev/chariot/commit/517c1c86545bd5e4a09f96907abd5838eecf8229
